---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install NodeJS
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Install npm
  ansible.builtin.apt:
    name: npm
    state: present